port毎に同じ名前のlocationを処理できるようにconfig.jsonの構造を変更（その２）
udzuki/spnego-nginx-auth-extension pull request #3
Opened 2024-02-10 02:11 UTC by mnagaku

# 詳細

https://github.com/udzuki/spnego-nginx-auth-extension/pull/2

の続き。

指摘事項に対応して、作業ブランチからのPRを作り直した。

# テスト内容

port違い同じlocationにconfig.jsonの通り異なるACLが効くことを実環境にて動作試験済み。

# チェックリスト

- [ ] 自身でコードレビューを実施済みであること
- [ ] 特に理解が困難な箇所について、適切なコメントを記述してあること
- [ ] コードの静的検証を実行し、摘出したエラーを全て対処してあること
- [ ] 必要なドキュメント修正が完了してあること
- [ ] 変更によって新たな警告が生じていないこと

2024-02-13 06:30 UTC, hiroki-sawano requested changes

2024-02-13 06:30 UTC, hiroki-sawano commented on README.adoc
> +<5> Add a header to pass the request port to the proxy.
```suggestion
<5> Add a header to pass the server port to the proxy.
```

2024-02-13 06:30 UTC, hiroki-sawano commented on auth.py
>      return None
ポートが定義されていない場合、 `KeyError` になって落ちます。
該当するポートがなければアクセス制限を課すべきではないため、後続の処理が期待通りに動作するように空の辞書を返すのはいかがでしょうか。
また、 #1 で見落としましたが、URLが見つからなかった時に返す値も同様です。

```suggestion
def get_entry(url, port):
    if port not in acl:
        return {}
    for k, v in acl[port].items():
        if url.startswith(k):
            return v
    return {}
```
※動作確認は未実施

2024-02-14 11:13 UTC, mnagaku commented on auth.py
>      return None
https://github.com/udzuki/spnego-nginx-auth-extension/blob/main/auth.py#L56

元々の実装では、entryが無かったらNoneになって、if entryでチェックして{}にしてるので、返すとしたら{}ではなくNoneかと思いましたが、如何でしょう？

2024-02-14 12:06 UTC, hiroki-sawano commented on auth.py
>      return None
あ、その通りですね。
返す値は `None` のままで良いです。勘違いしてました。
それでは以下だけ追加すれば良いかと思います。

```python
    if port not in acl:
        return None
```

2024-02-15 11:28 UTC, mnagaku commented on auth.py
>      return None
追加しました。

2024-02-16 03:32 UTC, hiroki-sawano approved these changes

2024-02-16 03:32 UTC, merged