最長一致かつ前方一致でエントリを取得
udzuki/spnego-nginx-auth-extension pull request #4
Opened 2024-02-16 11:50 UTC by mnagaku

# 詳細

/app1/と/app1/sub1/に異なるアクセス許可が付けられるように単なる前方一致ではなく最長一致を確認するように修正した。

# テスト内容

ほぼ同一のコードで期待挙動を確認済み。

# チェックリスト

- [ ] 自身でコードレビューを実施済みであること
- [ ] 特に理解が困難な箇所について、適切なコメントを記述してあること
- [ ] コードの静的検証を実行し、摘出したエラーを全て対処してあること
- [ ] 必要なドキュメント修正が完了してあること
- [ ] 変更によって新たな警告が生じていないこと

2024-03-02 08:52 UTC, hiroki-sawano requested changes

2024-03-02 08:52 UTC, hiroki-sawano commented on auth.py
>  def get_entry(url, port):
可読性を上げるリファクタリングの提案です。

```python
def get_entry(url, port):
    if port not in acl:
        return None
    longest_match = None
    max_length = 0
    for k, v in acl[port].items():
        if url.startswith(k) and len(k) > max_length:
            longest_match = v
            max_length = len(k)
    return longest_match
```

2024-03-02 08:52 UTC, hiroki-sawano commented on auth.py
>  def get_entry(url, port):
最長一致でルールを適用する仕様について、READMEの[このあたり](https://github.com/udzuki/spnego-nginx-auth-extension?tab=readme-ov-file#acl)に追記をお願いします。

2024-03-06 06:12 UTC, mnagaku commented
提案されたコードへの修正とreadmeへの追記を行いました。ご確認ください。

2024-03-15 08:20 UTC, hiroki-sawano approved these changes

2024-03-15 08:21 UTC, merged